### PR TITLE
yarn tests

### PR DESCRIPTION
**Pull request by cdmistman**
there's a bug with reading `@org/package` from the lockfile, which is why tests are failing

blocked on #126

### CODE REVIEW

**Comment by cdmistman** [comment]
😱 failing ci after merge???

**Comment by cdmistman** [comment]
ah crap bad merge

**Review by airportyh — COMMENTED** [review]
I am getting some test failures:
* TestAdd/nodejs-yarn/many-deps/unlocked/all
* TestList/nodejs-yarn/many-deps
* TestLock/nodejs-yarn

Among them.

**Review by airportyh — APPROVED** [review]
Sorry nm. I didn't have the nix-shell properly setup. Now it works.

**Pull request merged**
