### PR TITLE
Merge the conditions to remove duplicate code

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR merges the if / else if into one as the body of both branches of the condition is the same.

### CODE REVIEW

**Comment by raxod502** [comment]
This is vendored code so we probably shouldn't be touching it. It's taken directly from the distribution copy of Babel.

**Comment by DanielRuf** [comment]
So why is it in the sources / tracked then?

**Comment by raxod502** [comment]
Because the build system would be a lot more complicated and fragile otherwise.

**Comment by DanielRuf** [comment]
Hm, so no lockfiles? And we should not touch these files? So we can put them on the .gitignore file then to prevent that others touch them too?

**Comment by DanielRuf** [comment]
Hm, so no lockfiles? And we should not touch these files? So we can put them into the .gitignore file then to prevent that others touch them too?

**Comment by raxod502** [comment]
Your logic would be perfect in a Node.js project. There, it would make perfect sense to use the package manager to pull in the correct version of Babel. However, this isn't a Node.js project. It's a Go project, which needs to vendor code from Node.js, from Python, from Ruby, etc. It's simply not practical or desirable to say that in order to build this project, you need to install every package manager on your machine.

**Comment by DanielRuf** [comment]
No I meant that the vendor files can be added to the .gitignore file after adding them to prevent that others do the same mistake like I did.

**Pull request closed without merging**
